name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Debug Secrets (For troubleshooting only)
        run: |
          echo "DockerHub Username: ${{ secrets.DOCKERHUB_USER }}"
          echo "DockerHub Token: ${{ secrets.DOCKERHUB_TOKEN }}"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "polestar0"  # Directly pass the Docker Hub username
          password: "dckr_pat_is4XU-hy05qoPCdhzoIIXklOmEQ"  

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
